// <auto-generated />
namespace ClassLibrary1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v108));
        
        string IMigrationMetadata.Id
        {
            get { return "201712062057247_v1.0.8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
